configured_endpoints: 126
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/Southclaws%2Fstoryden-de9be3cabee985cf9a0f71ee64bb3ae4e78dbdab0c576535e5b0b4cfefab9e4a.yml
openapi_spec_hash: 1337a34f9ea96463421424e6923690c9
config_hash: bacac79e20c9bf16dbf8d735fe8be3c0
